# Generated by Django 3.1.4 on 2020-12-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='PostImage',
        ),
    ]
